# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_mixture_density_free <- function(x, params, log_p, param_sizes, comp_densities, is_discrete) {
    .Call(`_reservr_dist_mixture_density_free`, x, params, log_p, param_sizes, comp_densities, is_discrete)
}

dist_mixture_density_fixed <- function(x, params, log_p, param_sizes, comp_densities, is_discrete, probs) {
    .Call(`_reservr_dist_mixture_density_fixed`, x, params, log_p, param_sizes, comp_densities, is_discrete, probs)
}

dist_mixture_probability_free <- function(q, params, lower_tail, log_p, param_sizes, comp_probabilities) {
    .Call(`_reservr_dist_mixture_probability_free`, q, params, lower_tail, log_p, param_sizes, comp_probabilities)
}

dist_mixture_probability_fixed <- function(q, params, lower_tail, log_p, param_sizes, comp_probabilities, probs) {
    .Call(`_reservr_dist_mixture_probability_fixed`, q, params, lower_tail, log_p, param_sizes, comp_probabilities, probs)
}

dist_mixture_iprobability_free <- function(qmin, qmax, params, log_p, param_sizes, comp_iprobabilities) {
    .Call(`_reservr_dist_mixture_iprobability_free`, qmin, qmax, params, log_p, param_sizes, comp_iprobabilities)
}

dist_mixture_iprobability_fixed <- function(qmin, qmax, params, log_p, param_sizes, comp_iprobabilities, probs) {
    .Call(`_reservr_dist_mixture_iprobability_fixed`, qmin, qmax, params, log_p, param_sizes, comp_iprobabilities, probs)
}

dgamma_matrix <- function(x, shape, scale) {
    .Call(`_reservr_dgamma_matrix`, x, shape, scale)
}

pgamma_diff_matrix <- function(lower, upper, shape, scale) {
    .Call(`_reservr_pgamma_diff_matrix`, lower, upper, shape, scale)
}

trunc_erlangmix_ellik <- function(xmin, xmax, tmin, tmax, weight, shapes, scale, zadj, parallel) {
    .Call(`_reservr_trunc_erlangmix_ellik`, xmin, xmax, tmin, tmax, weight, shapes, scale, zadj, parallel)
}

do_integrate_gk_lst <- function(fun, lower, upper, params, tolerance, max_iter, debug) {
    .Call(`_reservr_do_integrate_gk_lst`, fun, lower, upper, params, tolerance, max_iter, debug)
}

do_integrate_gk_mat <- function(fun, lower, upper, params, tolerance, max_iter, debug) {
    .Call(`_reservr_do_integrate_gk_mat`, fun, lower, upper, params, tolerance, max_iter, debug)
}

softmax_mat <- function(x) {
    .Call(`_reservr_softmax_mat`, x)
}

softmax_vec <- function(x) {
    .Call(`_reservr_softmax_vec`, x)
}

dsoftmax_vec <- function(x) {
    .Call(`_reservr_dsoftmax_vec`, x)
}

