# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dgamma_matrix <- function(x, shape, scale) {
    .Call(`_reservr_dgamma_matrix`, x, shape, scale)
}

pgamma_diff_matrix <- function(lower, upper, shape, scale) {
    .Call(`_reservr_pgamma_diff_matrix`, lower, upper, shape, scale)
}

trunc_erlangmix_ellik <- function(xmin, xmax, tmin, tmax, weight, shapes, scale, zadj, parallel) {
    .Call(`_reservr_trunc_erlangmix_ellik`, xmin, xmax, tmin, tmax, weight, shapes, scale, zadj, parallel)
}

do_integrate_gk <- function(fun, lower, upper, params, tolerance, max_iter, parallel, debug) {
    .Call(`_reservr_do_integrate_gk`, fun, lower, upper, params, tolerance, max_iter, parallel, debug)
}

softmax_mat <- function(x) {
    .Call(`_reservr_softmax_mat`, x)
}

softmax_vec <- function(x) {
    .Call(`_reservr_softmax_vec`, x)
}

dsoftmax_vec <- function(x) {
    .Call(`_reservr_dsoftmax_vec`, x)
}

