# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_mixture_density_free <- function(x, params, log_p, param_sizes, comp_densities, is_discrete) {
    .Call(`_reservr_dist_mixture_density_free`, x, params, log_p, param_sizes, comp_densities, is_discrete)
}

dist_mixture_density_fixed <- function(x, params, log_p, param_sizes, comp_densities, is_discrete, probs) {
    .Call(`_reservr_dist_mixture_density_fixed`, x, params, log_p, param_sizes, comp_densities, is_discrete, probs)
}

dist_mixture_probability_free <- function(q, params, lower_tail, log_p, param_sizes, comp_probabilities) {
    .Call(`_reservr_dist_mixture_probability_free`, q, params, lower_tail, log_p, param_sizes, comp_probabilities)
}

dist_mixture_probability_fixed <- function(q, params, lower_tail, log_p, param_sizes, comp_probabilities, probs) {
    .Call(`_reservr_dist_mixture_probability_fixed`, q, params, lower_tail, log_p, param_sizes, comp_probabilities, probs)
}

dist_mixture_iprobability_free <- function(qmin, qmax, params, log_p, param_sizes, comp_iprobabilities) {
    .Call(`_reservr_dist_mixture_iprobability_free`, qmin, qmax, params, log_p, param_sizes, comp_iprobabilities)
}

dist_mixture_iprobability_fixed <- function(qmin, qmax, params, log_p, param_sizes, comp_iprobabilities, probs) {
    .Call(`_reservr_dist_mixture_iprobability_fixed`, qmin, qmax, params, log_p, param_sizes, comp_iprobabilities, probs)
}

dist_erlangmix_density_free <- function(x, params, log_p) {
    .Call(`_reservr_dist_erlangmix_density_free`, x, params, log_p)
}

dist_erlangmix_density_fixed_shape <- function(x, params, log_p, shapes) {
    .Call(`_reservr_dist_erlangmix_density_fixed_shape`, x, params, log_p, shapes)
}

dist_erlangmix_density_fixed_scale <- function(x, params, log_p, scale) {
    .Call(`_reservr_dist_erlangmix_density_fixed_scale`, x, params, log_p, scale)
}

dist_erlangmix_density_fixed_probs <- function(x, params, log_p, probs) {
    .Call(`_reservr_dist_erlangmix_density_fixed_probs`, x, params, log_p, probs)
}

dist_erlangmix_density_fixed_probs_scale <- function(x, params, log_p, probs, scale) {
    .Call(`_reservr_dist_erlangmix_density_fixed_probs_scale`, x, params, log_p, probs, scale)
}

dist_erlangmix_density_fixed_probs_shape <- function(x, params, log_p, probs, shapes) {
    .Call(`_reservr_dist_erlangmix_density_fixed_probs_shape`, x, params, log_p, probs, shapes)
}

dist_erlangmix_density_fixed_scale_shape <- function(x, params, log_p, scale, shapes) {
    .Call(`_reservr_dist_erlangmix_density_fixed_scale_shape`, x, params, log_p, scale, shapes)
}

dist_erlangmix_density_fixed_probs_scale_shape <- function(x, log_p, probs, scale, shapes) {
    .Call(`_reservr_dist_erlangmix_density_fixed_probs_scale_shape`, x, log_p, probs, scale, shapes)
}

dist_erlangmix_probability_free <- function(q, params, lower_tail, log_p) {
    .Call(`_reservr_dist_erlangmix_probability_free`, q, params, lower_tail, log_p)
}

dist_erlangmix_probability_fixed_shape <- function(q, params, lower_tail, log_p, shapes) {
    .Call(`_reservr_dist_erlangmix_probability_fixed_shape`, q, params, lower_tail, log_p, shapes)
}

dist_erlangmix_probability_fixed_scale <- function(q, params, lower_tail, log_p, scale) {
    .Call(`_reservr_dist_erlangmix_probability_fixed_scale`, q, params, lower_tail, log_p, scale)
}

dist_erlangmix_probability_fixed_probs <- function(q, params, lower_tail, log_p, probs) {
    .Call(`_reservr_dist_erlangmix_probability_fixed_probs`, q, params, lower_tail, log_p, probs)
}

dist_erlangmix_probability_fixed_probs_scale <- function(q, params, lower_tail, log_p, probs, scale) {
    .Call(`_reservr_dist_erlangmix_probability_fixed_probs_scale`, q, params, lower_tail, log_p, probs, scale)
}

dist_erlangmix_probability_fixed_probs_shape <- function(q, params, lower_tail, log_p, probs, shapes) {
    .Call(`_reservr_dist_erlangmix_probability_fixed_probs_shape`, q, params, lower_tail, log_p, probs, shapes)
}

dist_erlangmix_probability_fixed_scale_shape <- function(q, params, lower_tail, log_p, scale, shapes) {
    .Call(`_reservr_dist_erlangmix_probability_fixed_scale_shape`, q, params, lower_tail, log_p, scale, shapes)
}

dist_erlangmix_probability_fixed_probs_scale_shape <- function(q, lower_tail, log_p, probs, scale, shapes) {
    .Call(`_reservr_dist_erlangmix_probability_fixed_probs_scale_shape`, q, lower_tail, log_p, probs, scale, shapes)
}

dist_erlangmix_iprobability_free <- function(qmin, qmax, params, log_p) {
    .Call(`_reservr_dist_erlangmix_iprobability_free`, qmin, qmax, params, log_p)
}

dist_erlangmix_iprobability_fixed_shape <- function(qmin, qmax, params, log_p, shapes) {
    .Call(`_reservr_dist_erlangmix_iprobability_fixed_shape`, qmin, qmax, params, log_p, shapes)
}

dist_erlangmix_iprobability_fixed_scale <- function(qmin, qmax, params, log_p, scale) {
    .Call(`_reservr_dist_erlangmix_iprobability_fixed_scale`, qmin, qmax, params, log_p, scale)
}

dist_erlangmix_iprobability_fixed_probs <- function(qmin, qmax, params, log_p, probs) {
    .Call(`_reservr_dist_erlangmix_iprobability_fixed_probs`, qmin, qmax, params, log_p, probs)
}

dist_erlangmix_iprobability_fixed_probs_scale <- function(qmin, qmax, params, log_p, probs, scale) {
    .Call(`_reservr_dist_erlangmix_iprobability_fixed_probs_scale`, qmin, qmax, params, log_p, probs, scale)
}

dist_erlangmix_iprobability_fixed_probs_shape <- function(qmin, qmax, params, log_p, probs, shapes) {
    .Call(`_reservr_dist_erlangmix_iprobability_fixed_probs_shape`, qmin, qmax, params, log_p, probs, shapes)
}

dist_erlangmix_iprobability_fixed_scale_shape <- function(qmin, qmax, params, log_p, scale, shapes) {
    .Call(`_reservr_dist_erlangmix_iprobability_fixed_scale_shape`, qmin, qmax, params, log_p, scale, shapes)
}

dist_erlangmix_iprobability_fixed_probs_scale_shape <- function(qmin, qmax, log_p, probs, scale, shapes) {
    .Call(`_reservr_dist_erlangmix_iprobability_fixed_probs_scale_shape`, qmin, qmax, log_p, probs, scale, shapes)
}

dgamma_matrix <- function(x, shape, scale) {
    .Call(`_reservr_dgamma_matrix`, x, shape, scale)
}

pgamma_diff_matrix <- function(lower, upper, shape, scale) {
    .Call(`_reservr_pgamma_diff_matrix`, lower, upper, shape, scale)
}

trunc_erlangmix_ellik <- function(xmin, xmax, tmin, tmax, weight, shapes, scale, zadj, parallel) {
    .Call(`_reservr_trunc_erlangmix_ellik`, xmin, xmax, tmin, tmax, weight, shapes, scale, zadj, parallel)
}

do_integrate_gk_lst <- function(fun, lower, upper, params, tolerance, max_iter, debug) {
    .Call(`_reservr_do_integrate_gk_lst`, fun, lower, upper, params, tolerance, max_iter, debug)
}

do_integrate_gk_mat <- function(fun, lower, upper, params, tolerance, max_iter, debug) {
    .Call(`_reservr_do_integrate_gk_mat`, fun, lower, upper, params, tolerance, max_iter, debug)
}

softmax_mat <- function(x) {
    .Call(`_reservr_softmax_mat`, x)
}

softmax_vec <- function(x) {
    .Call(`_reservr_softmax_vec`, x)
}

dsoftmax_vec <- function(x) {
    .Call(`_reservr_dsoftmax_vec`, x)
}

